name: ufoai
title: UFOAI game build for Snap 
base: core22
license: MIT
summary: UFOAI game build for Snap  
description: |
  **UFOAI** game build for Snap 
grade: stable 
confinement: strict
website: https://github.com/fenenko/ufoai
issues: https://github.com/fenenko/ufoai/issues 
source-code: https://github.com/fenenko/ufoai
version: '2.5.0'

apps:
  ufoai:           
    command: ufoai
    common-id: com.github.fenenko.ufoai 
    extensions: [gnome]
    plugs:             
      - desktop
      - home
      - network
      - x11
      - wayland

parts:
  ufoai-app:       
    plugin: nil
    source: https://github.com/fenenko/ufoai
    source-type: git
    build-packages: []
    stage-packages:
      - ufoai
    override-build: |  
      echo "START BUILD"

