name: Build Snap Package

on:
  workflow_dispatch:
  push:
    paths:
      - 'snap/**'
  pull_request:
    paths:
      - 'snap/**'

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Snap
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-snap
          path: ${{ steps.snapcraft.outputs.snap }}
